runtime: python
vm: true
# main:APP = a variable named APP (the web app) in main.py module.
entrypoint: gunicorn -b :$PORT main:APP

runtime_config:
  python_version: 2

manual_scaling:
  instances: 1

#to get a f1-micro instance
resources:
  cpu: .5
  memory_gb: 1.0
  disk_size_gb: 10

env_variables:
    GCLOUD_PROJECT: gator-01
    NLTK_DATA: ./nltk_data

skip_files:
  # gae default (cf. https://cloud.google.com/appengine/docs/python/config/appref#skip_files)
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  # app specific
  - ^tests$