runtime: python
vm: true
# In the last parameter passed to gunicorn,
# - main is the module name (the associated file is thus main.py) containing the web app
# - APP is the variable name of the web app in the module
entrypoint: gunicorn -b :$PORT main:APP

runtime_config:
  python_version: 3

#to get a f1-micro instance
resources:
  cpu: .5
  memory_gb: .19
  disk_size_gb: 10

env_variables:
    GCLOUD_PROJECT: gator-01

skip_files:
    - ^tests$