language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test_requirements.txt --use-mirrors"

#download and unzip GAE SDK in directory google_appengine
before_script:
  - wget http://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.22.zip -nv
  - unzip -q google_appengine_1.9.22.zip


# command to run tests
script: py.test
