language: python
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_411bc28b64b2_key -iv $encrypted_411bc28b64b2_iv
  -in client-secret.json.enc -out client-secret.json -d
- mkdir lib_travis
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p ./lib_travis/miniconda
- export PATH=$(pwd)/lib_travis/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION cryptography numpy scipy
- tools/install_envs.sh
- pip install coveralls
script:
- ./tools/start_tests.sh
- python tools/run_pylint.py src
- ./tools/start_tests.sh cover
after_success:
- coveralls
deploy:
  provider: gae
  keyfile: client-secret.json
  project: gator-01
  default: true
  config: src/server/app.yaml
