language: python
sudo: required
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_411bc28b64b2_key -iv $encrypted_411bc28b64b2_iv
  -in client-secret.json.enc -out client-secret.json -d
- mkdir lib
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p ./lib/miniconda
- export PATH=$(pwd)/lib/miniconda/bin:$PATH
- conda update --yes conda
- wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-113.0.0-linux-x86_64.tar.gz
  -nv
- tar zxvf google-cloud-sdk-113.0.0-linux-x86_64.tar.gz -C lib
- export PATH=$(pwd)/lib/google-cloud-sdk/bin:$PATH
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION cryptography numpy scipy
- tools/install_envs.sh
- pip install coveralls
script:
- ./tools/start_tests.sh
- python tools/run_pylint.py src
- ./tools/start_tests.sh cover
after_success:
- coveralls
deploy:
  provider: gae
  keyfile: client-secret.json
  project: gator-01
  default: true
  config: src/server/server/app.yaml
