language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
  - "pip install coveralls"

#download and unzip GAE SDK in directory google_appengine
before_script:
  - mkdir lib
  - wget http://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.22.zip -nv
  - unzip -q google_appengine_1.9.22.zip -d lib
  - ./lib/google_appengine/dev_appserver.py ./src/server/server/ --skip_sdk_update_check &
  - sleep 3 # give server some time to start


# command to run tests
script:
  - py.test src
  - coverage run --source=src --omit=*tests* -m py.test src
  - pylint src/server/server src/server/tests src/functests

after_success:
  - coveralls