language: python

python:
  - "2.7"

env:
- GAE_SDK_PATH=./google_appengine

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"

#download and unzip GAE SDK in directory google_appengine
before_script:
  - wget http://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.22.zip -nv
  - unzip -q google_appengine_1.9.22.zip
  - ./google_appengine/dev_appserver.py ./src/server/server/


# command to run tests
script: py.test src
