language: python
python:
- '2.7'
before_install:
- mkdir lib
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p ./lib/miniconda
- export PATH=$(pwd)/lib/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION cryptography numpy scipy
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install -e src/common -e src/scraper -e src/server -e src/topicmodeller -e src/learner -e src/orchestrator
- pip install coveralls
- python -m nltk.downloader stopwords
- python -m nltk.downloader punkt
before_script:
- wget http://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.28.zip -nv
- unzip -q google_appengine_1.9.28.zip -d lib
# symblic link between the 2 locations where "google" is a root of python packages (to make 'import google.*' work)
- export GOOGLE_PIP_DIR=$(pip show protobuf | grep Location | awk {'print $2'})/google
- ln -s $(pwd)/lib/google_appengine/google/appengine $GOOGLE_PIP_DIR/appengine
- ln -s $(pwd)/lib/google_appengine/google/net $GOOGLE_PIP_DIR/net
- ./tools/start_gae.sh &
- sleep 3
script:
- py.test src
- coverage run --source=src --omit=*tests* -m py.test src
- ./tools/run_pylint.py src/
after_success:
- coveralls
- if [[ ("${TRAVIS_BRANCH}" = "master") &&  ("${TRAVIS_PULL_REQUEST}" = "false") ]]; then ./lib/google_appengine/appcfg.py -A gator-01 --skip_sdk_update_check --oauth2_access_token=$GAE_TOKEN --oauth2_refresh_token=$GAE_REFRESH_TOKEN update ./src/server/server; fi
