runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:APP

runtime_config:
  python_version: 2

#to get a f1-micro instance
resources:
  cpu: .5
  memory_gb: .19
  disk_size_gb: 10

env_variables:
    GCLOUD_PROJECT: gator-01

